// =============================================
//  watchlist.js — MockAPI CRUD Module
//
//  PURPOSE:
//  Handles all communication with MockAPI, which
//  acts as our persistent backend/database for the
//  user's watchlist. Every watchlist entry is
//  stored as a JSON object on MockAPI's servers.
//
//  WHY MOCKAPI?
//  The project requires a real REST API with GET,
//  POST, PUT, and DELETE. MockAPI provides a free,
//  instant REST endpoint with no server setup.
//  It behaves exactly like a real backend API.
//
//  HTTP METHODS USED:
//  GET    /watchlist        → getAll()      — load all entries
//  GET    /watchlist/:id    → getById()     — load one entry
//  POST   /watchlist        → add()         — create new entry
//  PUT    /watchlist/:id    → update()      — edit an entry
//  DELETE /watchlist/:id    → remove()      — delete an entry
//
//  WATCHLIST ENTRY SCHEMA:
//  {
//    id:          string   — auto-generated by MockAPI
//    tmdbId:      string   — TMDB movie ID (for linking back)
//    title:       string   — movie title
//    posterPath:  string   — TMDB poster path (e.g. '/abc.jpg')
//    releaseYear: string   — e.g. '2023'
//    rating:      string   — TMDB vote average e.g. '8.4'
//    status:      string   — 'Want to Watch' | 'Watching' | 'Completed'
//    note:        string   — user's personal note (optional)
//    addedAt:     string   — ISO timestamp of when it was added
//  }
//
//  DEPENDS ON: config.js (must load first)
// =============================================

const WatchlistAPI = (() => {
  // Build the full endpoint URL dynamically from CONFIG
  // This way, changing the base URL or resource name in
  // config.js automatically updates all requests here
  const baseUrl = () =>
    `${CONFIG.MOCKAPI_BASE_URL}/${CONFIG.MOCKAPI_RESOURCE}`;

  // --------------------------------------------------
  //  getAll() — GET /watchlist
  //  Fetches every entry in the watchlist.
  //  Called when the watchlist page loads.
  //  @returns {Promise<Array>} array of entry objects
  // --------------------------------------------------
  const getAll = async () => {
    const res = await fetch(baseUrl());
    if (!res.ok) throw new Error(`Failed to fetch watchlist (${res.status})`);
    return res.json();
  };

  // --------------------------------------------------
  //  getById() — GET /watchlist/:id
  //  Fetches a single entry by its MockAPI-generated id.
  //  Not currently used in the UI but available for
  //  future features (e.g. a dedicated entry view).
  //  @param {string} id — MockAPI entry id
  // --------------------------------------------------
  const getById = async (id) => {
    const res = await fetch(`${baseUrl()}/${id}`);
    if (!res.ok) throw new Error(`Entry not found (${res.status})`);
    return res.json();
  };

  // --------------------------------------------------
  //  add() — POST /watchlist
  //  Creates a new watchlist entry.
  //  Called when the user clicks "Add to Watchlist"
  //  on the movie detail page.
  //
  //  We must set Content-Type: application/json so
  //  MockAPI knows to parse the request body as JSON.
  //
  //  @param {object} entry — the watchlist entry object
  //  @returns {Promise<object>} the created entry (with id)
  // --------------------------------------------------
  const add = async (entry) => {
    const res = await fetch(baseUrl(), {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(entry), // serialize JS object → JSON string
    });
    if (!res.ok) throw new Error(`Failed to add entry (${res.status})`);
    return res.json();
  };

  // --------------------------------------------------
  //  update() — PATCH /watchlist/:id
  //  Updates an existing entry's fields.
  //  Called when the user saves changes in the
  //  inline edit form on the watchlist page.
  //  Only the fields passed in `changes` are updated.
  //
  //  @param {string} id      — MockAPI entry id
  //  @param {object} changes — fields to update
  //  @returns {Promise<object>} the updated entry
  // --------------------------------------------------
  const update = async (id, changes) => {
    const res = await fetch(`${baseUrl()}/${id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(changes),
    });
    if (!res.ok) throw new Error(`Failed to update entry (${res.status})`);
    return res.json();
  };

  // --------------------------------------------------
  //  remove() — DELETE /watchlist/:id
  //  Permanently deletes an entry from MockAPI.
  //  Called after the user confirms deletion in the
  //  modal dialog on the watchlist page.
  //
  //  @param {string} id — MockAPI entry id
  // --------------------------------------------------
  const remove = async (id) => {
    const res = await fetch(`${baseUrl()}/${id}`, {
      method: 'DELETE',
    });
    if (!res.ok) throw new Error(`Failed to delete entry (${res.status})`);
    return res.json();
  };

  // --------------------------------------------------
  //  findByTmdbId() — utility: check for duplicates
  //  Fetches all entries then finds one matching the
  //  given TMDB movie ID. Used on the movie detail page
  //  to detect if a film is already in the watchlist,
  //  so we can show "✓ In Watchlist" instead of the
  //  "Add" button.
  //
  //  Note: We compare as strings because MockAPI may
  //  return IDs as strings even if stored as numbers.
  //
  //  @param {string|number} tmdbId
  //  @returns {Promise<object|null>}
  // --------------------------------------------------
  const findByTmdbId = async (tmdbId) => {
    const all = await getAll();
    return all.find((entry) => String(entry.tmdbId) === String(tmdbId)) || null;
  };

  // Expose all public methods
  return { getAll, getById, add, update, remove, findByTmdbId };
})();
